alias la="ls -a"
alias ll="ls -l"
alias home="cd ~"
alias project="cd /mnt/c/users/thms/Documents/Projects"
alias projects="project"
alias downloads="cd /mnt/c/users/thms/Downloads"
alias predev="git checkout pre-development"
alias prevb="git checkout @{-1}"
alias prevb1="git checkout @{-1}"
alias prevb2="git checkout @{-2}"
alias prevb3="git checkout @{-3}"

